# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aa73a2fd272def526a3cf0dfbeb24372fc3e0c3357531542267d3f1de603ac6093fae9f56ab7222440957a0aeeefe04381348b2811e503121ada31e81fc525f5

test:
  secret_key_base: 1ccd4fcce95921c6544a1192fbbc0608eba5a82bff5e4d5f02d883f1f0d4811b4c3eab95aa0392e67700e88bba06bdf1855ef6c9a21791ff0068fc8679aa2f37

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
